FROM --platform=$BUILDPLATFORM alpine as build-env

RUN apk add --no-cache build-base

ARG TARGETARCH
RUN if [ "$TARGETARCH" == "arm64" ]; \
        then apk add --no-cache gcc-arm-none-eabi newlib-arm-none-eabi; \
    fi

WORKDIR /app
COPY . .

RUN if [ "$TARGETARCH" == "amd64" ]; \
        then gcc FibCalc.c -lm -o FibCalc; \
    elif [ "$TARGETARCH" == "arm64" ]; \
        then arm-none-eabi-gcc FibCalc.c --specs=nosys.specs -lm -o FibCalc; \
    fi

FROM alpine

COPY --from=build-env /app/FibCalc /app/FibCalc
WORKDIR /app

CMD ["/app/FibCalc"]