name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=docker.io/nikesz/fibcalc:buildcache
          cache-to: type=registry,ref=docker.io/nikesz/fibcalc:buildcache
          platforms: linux/amd64,linux/arm64
          context: ./
          push: true
          tags: |
            nikesz/fibcalc
            ghcr.io/thenikesz/fibcalc